import markdown from "../../generated/docs/Gallery.md?raw";
import type { ComponentSource } from "../registry";

export default {
  name: "Gallery",
  markdown,
  storybook: "components-images-and-icons-gallery--basic",
  source: "Gallery/Gallery.tsx",
  // A full-screen viewer would take the whole window; 500px shows it in full and keeps the page in sight.
  previewMaxHeight: 500,
  example: `<Gallery
  files={[
    {
      key: "abc",
      name: "myballisbigandroundIamrollingitontheground.png",
      type: "image/png",
      size: 213402324,
      progress: 1,
      thumbnailSrc: "https://picsum.photos/250",
      src: "https://picsum.photos/550",
    },
    {
      key: "def",
      name: "iamanimage.png",
      type: "image/png",
      size: 124525234,
      progress: 1,
      thumbnailSrc: "https://picsum.photos/250",
      src: "https://picsum.photos/550",
    },
    {
      key: "efg",
      name: "upanddown.png",
      type: "image/png",
      size: 233411234,
      progress: 1,
      thumbnailSrc: "https://picsum.photos/250",
      src: "https://picsum.photos/550",
    },
    {
      key: "jkl",
      name: "kramer.png",
      type: "image/png",
      size: 233411234,
      progress: 1,
      thumbnailSrc: "https://picsum.photos/250",
      src: "https://picsum.photos/550",
    },
    {
      key: "mno",
      name: "boston.png",
      type: "image/png",
      size: 233411234,
      progress: 1,
      thumbnailSrc: "https://picsum.photos/250",
      src: "https://picsum.photos/550",
    },
    {
      key: "pqr",
      name: "pizzaisgood.png",
      type: "image/png",
      size: 233411234,
      progress: 1,
      thumbnailSrc: "https://picsum.photos/250",
      src: "https://picsum.photos/550",
    },
    {
      key: "pQ=",
      name: "avatar.png",
      type: "image/png",
      size: 233411234,
      progress: 1,
      thumbnailSrc: "https://picsum.photos/250",
      src: "https://picsum.photos/550",
    },
    {
      key: "fGr",
      name: "whatevenisthat.png",
      type: "image/png",
      size: 233411234,
      progress: 1,
      thumbnailSrc: "https://picsum.photos/250",
      src: "https://picsum.photos/550",
    },
    {
      key: "AM=",
      name: "stairs.png",
      type: "image/png",
      size: 233411234,
      progress: 1,
      thumbnailSrc: "https://picsum.photos/250",
      src: "https://picsum.photos/550",
    },
  ]}
/>`,
} satisfies ComponentSource;
