// The site's page lists: each page's title, link, card image, nav sections and extra search terms.
export interface ContentListItem {
  readonly title: string;
  readonly to: string;
  readonly imageURL?: string;
  readonly sections?: readonly string[];
  readonly additionalMatches?: readonly string[];
}

export const componentList: readonly ContentListItem[] = [
  {
    title: "ActionItem",
    to: "/components/ActionItem",
    imageURL: "/ActionItem.avif",
    sections: ["Layouts & Structure"],
  },
  {
    title: "ActionItemGroup",
    to: "/components/ActionItemGroup",
    imageURL: "/ActionItemGroup.avif",
    sections: ["Layouts & Structure"],
  },
  {
    title: "ActionLabel",
    to: "/components/ActionLabel",
    imageURL: "/ActionLabel.avif",
    sections: ["Actions"],
    additionalMatches: ["Button"],
  },
  {
    title: "ActivityIndicator",
    to: "/components/ActivityIndicator",
    imageURL: "/ActivityIndicator.avif",
    sections: ["Status & Feedback"],
    additionalMatches: ["Loader", "Loading", "Busy", "Spinner"],
  },
  {
    title: "AtlantisThemeContext",
    to: "/components/AtlantisThemeContext",
    imageURL: "/AtlantisThemeContext.avif",
    additionalMatches: ["Theme", "Dark Mode", "Light Mode"],
    sections: ["Themes"],
  },
  {
    title: "Autocomplete",
    to: "/components/Autocomplete",
    imageURL: "/Autocomplete.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Search", "Typeahead", "Suggest"],
  },
  {
    title: "AutoLink",
    to: "/components/AutoLink",
    imageURL: "/AutoLink.avif",
    sections: ["Text & Typography"],
    additionalMatches: ["Link", "URL", "Text", "Phone", "Email"],
  },
  {
    title: "Avatar",
    to: "/components/Avatar",
    imageURL: "/Avatar.avif",
    sections: ["Images & Icons"],
    additionalMatches: ["User", "Facepile", "Profile"],
  },
  {
    title: "Banner",
    to: "/components/Banner",
    imageURL: "/Banner.avif",
    sections: ["Status & Feedback"],
    additionalMatches: ["Flash", "Alert", "Notification", "Hero"],
  },
  {
    title: "Box",
    to: "/components/Box",
    imageURL: "/Box.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "BottomSheet",
    to: "/components/BottomSheet",
    imageURL: "/BottomSheet.avif",
    sections: ["Selections"],
    additionalMatches: ["Drawer", "Panel", "Overlay", "Modal"],
  },
  {
    title: "Button",
    to: "/components/Button",
    imageURL: "/Button.avif",
    sections: ["Actions"],
    additionalMatches: ["Action"],
  },
  {
    title: "ButtonDismiss",
    to: "/components/ButtonDismiss",
    imageURL: "/ButtonDismiss.avif",
    additionalMatches: ["Close", "Dismiss", "Remove"],
    sections: ["Private"],
  },
  {
    title: "ButtonGroup",
    to: "/components/ButtonGroup",
    imageURL: "/ButtonGroup.avif",
    sections: ["Actions"],
    additionalMatches: ["Action", "Layout", "Wrapper"],
  },
  {
    title: "Card",
    to: "/components/Card",
    imageURL: "/Card.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Tile"],
  },
  {
    title: "ContentBlock",
    to: "/components/ContentBlock",
    imageURL: "/ContentBlock.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "Checkbox",
    to: "/components/Checkbox",
    imageURL: "/Checkbox.avif",
    sections: ["Selections"],
    additionalMatches: ["Select"],
  },
  {
    title: "Chip",
    to: "/components/Chip",
    imageURL: "/Chip.avif",
    sections: ["Selections"],
    additionalMatches: ["Pill", "Badge", "Tag", "Select"],
  },
  {
    title: "Chips",
    to: "/components/Chips",
    imageURL: "/Chips.avif",
    additionalMatches: ["Pill", "Badge", "Tag"],
    sections: ["Selections"],
  },
  {
    title: "Combobox",
    to: "/components/Combobox",
    imageURL: "/FilterPicker.avif",
    sections: ["Selections"],
    additionalMatches: ["Dropdown", "Picker", "Select", "Search", "Typeahead"],
  },
  {
    title: "Cluster",
    to: "/components/Cluster",
    imageURL: "/Cluster.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Grid", "Columns", "Rows"],
  },
  {
    title: "FilterPicker",
    to: "/components/FilterPicker",
    imageURL: "/FilterPicker.avif",
    sections: ["Selections"],
    additionalMatches: ["Combobox", "Dropdown", "Picker", "Select"],
  },
  {
    title: "ConfirmationModal",
    to: "/components/ConfirmationModal",
    imageURL: "/ConfirmationModal.avif",
    additionalMatches: ["Confirm", "Prompt", "Modal"],
    sections: ["Overlays"],
  },
  {
    title: "Container",
    to: "/components/Container",
    imageURL: "/Container.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Query"],
  },
  {
    title: "Content",
    to: "/components/Content",
    imageURL: "/Content.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Stack", "Layout", "Container", "Wrapper", "Spacing"],
  },
  {
    title: "ContentOverlay",
    to: "/components/ContentOverlay",
    imageURL: "/ContentOverlay.avif",
    sections: ["Overlays"],
  },
  {
    title: "Countdown",
    to: "/components/Countdown",
    imageURL: "/Countdown.avif",
    sections: ["Utilities"],
    additionalMatches: ["Timer", "Time", "Clock"],
  },
  {
    title: "Cover",
    to: "/components/Cover",
    imageURL: "/Cover.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "Dialog",
    to: "/components/Dialog",
    imageURL: "/Modal.avif",
    sections: ["Overlays"],
    additionalMatches: ["Modal", "Popup", "Overlay", "Confirm", "Alert"],
  },
  {
    title: "DataDump",
    to: "/components/DataDump",
    imageURL: "/DataDump.avif",
    sections: ["Utilities"],
  },
  {
    title: "DataList",
    to: "/components/DataList",
    imageURL: "/DataList.avif",
    sections: ["Lists & Tables"],
    additionalMatches: ["Thicklist", "Table"],
  },
  {
    title: "DataTable",
    to: "/components/DataTable",
    imageURL: "/DataTable.avif",
    sections: ["Lists & Tables"],
    additionalMatches: ["Thicklist", "Table"],
  },
  {
    title: "DatePicker",
    to: "/components/DatePicker",
    imageURL: "/DatePicker.avif",
    sections: ["Selections"],
    additionalMatches: ["Calendar", "Date Picker", "Date Input"],
  },
  {
    title: "Disclosure",
    to: "/components/Disclosure",
    imageURL: "/Disclosure.avif",
    additionalMatches: ["Accordion", "Collapsable", "Expandable", "Toggle", "Reveal"],
    sections: ["Layouts & Structure"],
  },
  {
    title: "Divider",
    to: "/components/Divider",
    imageURL: "/Divider.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Separator", "Line", "Rule", "Border", "HR"],
  },
  {
    title: "Drawer",
    to: "/components/Drawer",
    imageURL: "/Drawer.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Aside", "Panel", "Flyout"],
  },
  {
    title: "Emphasis",
    to: "/components/Emphasis",
    imageURL: "/Emphasis.avif",
    additionalMatches: ["Highlight", "Strong", "Bold", "Italic"],
    sections: ["Text & Typography"],
  },
  {
    title: "EmptyState",
    to: "/components/EmptyState",
    imageURL: "/EmptyState.avif",
    additionalMatches: ["No", "None", "Nada", "Nothing"],
    sections: ["Status & Feedback"],
  },
  {
    title: "FeatureSwitch",
    to: "/components/FeatureSwitch",
    imageURL: "/FeatureSwitch.avif",
    sections: ["Selections"],
  },
  {
    title: "Flex",
    to: "/components/Flex",
    imageURL: "/Flex.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Stack", "Container"],
  },
  {
    title: "Frame",
    to: "/components/Frame",
    imageURL: "/Frame.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Stack", "Container"],
  },
  {
    title: "Form",
    to: "/components/Form",
    imageURL: "/Form.avif",
    sections: ["Forms & Inputs"],
  },
  {
    title: "FormatFile",
    to: "/components/FormatFile",
    imageURL: "/FormatFile.avif",
    sections: ["Images & Icons"],
    additionalMatches: ["Display", "Upload", "Thumbnail", "Image"],
  },
  {
    title: "FormField",
    to: "/components/FormField",
    imageURL: "/FormField.avif",
    sections: ["Private"],
  },
  {
    title: "Gallery",
    to: "/components/Gallery",
    imageURL: "/Gallery.avif",
    sections: ["Images & Icons"],
    additionalMatches: ["ThumbnailList", "ImageList", "Carousel", "Image", "Thumbnail", "Photo"],
  },
  {
    title: "Glimmer",
    to: "/components/Glimmer",
    imageURL: "/Glimmer.avif",
    additionalMatches: ["Skeleton", "Shimmer"],
    sections: ["Status & Feedback"],
  },
  {
    title: "Grid",
    to: "/components/Grid",
    imageURL: "/Grid.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Columns"],
  },
  {
    title: "Heading",
    to: "/components/Heading",
    imageURL: "/Heading.avif",
    sections: ["Text & Typography"],
    additionalMatches: ["Title", "Subtitle", "Header", "H1", "H2", "H3", "H4", "H5", "H6"],
  },
  {
    title: "Icon",
    to: "/components/Icon",
    imageURL: "/Icon.avif",
    sections: ["Images & Icons"],
    additionalMatches: ["Symbol"],
  },
  {
    title: "IconButton",
    to: "/components/IconButton",
    imageURL: "/IconButton.avif",
    sections: ["Actions"],
  },
  {
    title: "InlineLabel",
    to: "/components/InlineLabel",
    imageURL: "/InlineLabel.avif",
    additionalMatches: ["Tag", "Label", "Chip", "Badge", "Pill", "Status Label", "Status"],
    sections: ["Status & Feedback"],
  },
  {
    title: "InputAvatar",
    to: "/components/InputAvatar",
    imageURL: "/InputAvatar.avif",
    sections: ["Forms & Inputs"],
  },
  {
    title: "InputCurrency",
    to: "/components/InputCurrency",
    imageURL: "/InputCurrency.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Money", "Dollar", "Currency"],
  },
  {
    title: "InputDate",
    to: "/components/InputDate",
    imageURL: "/InputDate.avif",
    additionalMatches: ["Datepicker", "Datetime Picker", "Calendar"],
    sections: ["Forms & Inputs"],
  },
  {
    title: "InputEmail",
    to: "/components/InputEmail",
    imageURL: "/InputEmail.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Email Input"],
  },
  {
    title: "InputFieldWrapper",
    to: "/components/InputFieldWrapper",
    imageURL: "/InputFieldWrapper.avif",
    sections: ["Private"],
  },
  {
    title: "InputFile",
    to: "/components/InputFile",
    imageURL: "/InputFile.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Uploader", "File Input", "File Uploader", "Upload", "Dropzone", "Image"],
  },
  {
    title: "InputGroup",
    to: "/components/InputGroup",
    imageURL: "/InputGroup.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Fieldset"],
  },
  {
    title: "InputNumber",
    to: "/components/InputNumber",
    imageURL: "/InputNumber.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Number Input", "Numeric Input"],
  },
  {
    title: "InputPassword",
    to: "/components/InputPassword",
    imageURL: "/InputPassword.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Password Input"],
  },
  {
    title: "InputPhoneNumber",
    to: "/components/InputPhoneNumber",
    imageURL: "/InputPhoneNumber.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Phone Number Input"],
  },
  {
    title: "InputPressable",
    to: "/components/InputPressable",
    imageURL: "/InputPressable.avif",
    sections: ["Forms & Inputs"],
  },
  {
    title: "InputSearch",
    to: "/components/InputSearch",
    imageURL: "/InputSearch.avif",
    sections: ["Forms & Inputs"],
  },
  {
    title: "InputText",
    to: "/components/InputText",
    imageURL: "/InputText.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Textfield", "Text Input", "Input", "Textbox", "Textarea", "Field"],
  },
  {
    title: "InputTime",
    to: "/components/InputTime",
    imageURL: "/InputTime.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Time Input", "Time Picker"],
  },
  {
    title: "InputValidation",
    to: "/components/InputValidation",
    imageURL: "/InputValidation.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Field Error", "Error Message"],
  },
  {
    title: "LightBox",
    to: "/components/LightBox",
    imageURL: "/LightBox.avif",
    sections: ["Images & Icons"],
    additionalMatches: ["Gallery", "Carousel", "Display", "Image", "Box Sizing", "Border Box"],
  },
  {
    title: "Link",
    to: "/components/Link",
    imageURL: "/Link.avif",
    additionalMatches: ["Anchor", "URL"],
    sections: ["Text & Typography"],
  },
  {
    title: "List",
    to: "/components/List",
    imageURL: "/List.avif",
    sections: ["Lists & Tables"],
  },
  {
    title: "Markdown",
    to: "/components/Markdown",
    imageURL: "/Markdown.avif",
    sections: ["Text & Typography"],
    additionalMatches: ["Text"],
  },
  {
    title: "Menu",
    to: "/components/Menu",
    imageURL: "/Menu.avif",
    sections: ["Navigation"],
    additionalMatches: ["Dropdown"],
  },
  {
    title: "Modal",
    to: "/components/Modal",
    imageURL: "/Modal.avif",
    sections: ["Deprecated"],
    additionalMatches: ["Dialog", "Popup", "Overlay", "Confirm", "Alert"],
  },
  {
    title: "MultiSelect",
    to: "/components/MultiSelect",
    imageURL: "/MultiSelect.avif",
    sections: ["Deprecated"],
    additionalMatches: ["Dropdown", "Menu"],
  },
  {
    title: "Page",
    to: "/components/Page",
    imageURL: "/Page.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container"],
  },
  {
    title: "Popover",
    to: "/components/Popover",
    imageURL: "/Popover.avif",
    sections: ["Overlays"],
    additionalMatches: ["Dropdown", "Popup", "Tooltip", "Float", "Dialog", "Info"],
  },
  {
    title: "ProgressBar",
    to: "/components/ProgressBar",
    imageURL: "/ProgressBar.avif",
    sections: ["Status & Feedback"],
    additionalMatches: ["Progress", "Loader", "Stepper", "ProgressIndicator"],
  },
  {
    title: "ProgressIndicator",
    to: "/components/ProgressIndicator",
    imageURL: "/ProgressBar.avif",
    sections: ["Status & Feedback"],
    additionalMatches: ["Progress", "Loader", "Stepper", "ProgressBar"],
  },
  {
    title: "RadioGroup",
    to: "/components/RadioGroup",
    imageURL: "/RadioGroup.avif",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Radio Button", "Select"],
  },
  {
    title: "ResponsiveSwitcher",
    to: "/components/ResponsiveSwitcher",
    imageURL: "/ResponsiveSwitcher.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "SegmentedControl",
    to: "/components/SegmentedControl",
    imageURL: "/SegmentedControl.avif",
    sections: ["Selections"],
    additionalMatches: ["Toggle", "Switch", "ViewControl", "TabControl", "Tab"],
  },
  {
    title: "Select",
    to: "/components/Select",
    imageURL: "/Select.avif",
    sections: ["Selections"],
    additionalMatches: ["Dropdown", "Picker", "Menu", "Combobox"],
  },
  {
    title: "LegacySelect",
    to: "/components/LegacySelect",
    imageURL: "/Select.avif",
    sections: ["Selections"],
    additionalMatches: ["Select", "Dropdown", "Picker", "Menu"],
  },
  {
    title: "SelectPrimitive",
    to: "/components/SelectPrimitive",
    imageURL: "/Select.avif",
    sections: ["Primitives"],
    additionalMatches: ["Select", "Dropdown", "Picker"],
  },
  {
    title: "SideDrawer",
    to: "/components/SideDrawer",
    imageURL: "/SideDrawer.avif",
    sections: ["Overlays"],
    additionalMatches: ["Drawer", "Panel", "Sidebar", "Flyout"],
  },
  {
    title: "SideKick",
    to: "/components/SideKick",
    imageURL: "/Sidekick.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "Spinner",
    to: "/components/Spinner",
    imageURL: "/Spinner.avif",
    sections: ["Status & Feedback"],
    additionalMatches: ["Loader", "Loading", "Twirly", "Wait", "Busy", "ActivityIndicator"],
  },
  {
    title: "Stack",
    to: "/components/Stack",
    imageURL: "/Stack.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "StatusIndicator",
    to: "/components/StatusIndicator",
    imageURL: "/StatusIndicator.avif",
    sections: ["Status & Feedback"],
    additionalMatches: ["Badge", "Tag"],
  },
  {
    title: "StatusLabel",
    to: "/components/StatusLabel",
    imageURL: "/StatusLabel.avif",
    additionalMatches: ["Badge", "Pill", "Tag", "InlineLabel", "Inline Label"],
    sections: ["Status & Feedback"],
  },
  {
    title: "Switch",
    to: "/components/Switch",
    imageURL: "/Switch.avif",
    additionalMatches: ["Toggle"],
    sections: ["Selections"],
  },
  {
    title: "Table",
    to: "/components/Table",
    imageURL: "/Table.avif",
    sections: ["Lists & Tables"],
  },
  {
    title: "Tabs",
    to: "/components/Tabs",
    imageURL: "/Tabs.avif",
    sections: ["Navigation"],
    additionalMatches: ["Segmented Control"],
  },
  {
    title: "Text",
    to: "/components/Text",
    imageURL: "/Text.avif",
    sections: ["Text & Typography"],
    additionalMatches: ["Paragraph", "Body Copy", "Typography"],
  },
  {
    title: "TextList",
    to: "/components/TextList",
    imageURL: "/TextList.avif",
    sections: ["Lists & Tables"],
    additionalMatches: ["Bullet", "Unordered", "Ordered"],
  },
  {
    title: "ThumbnailList",
    to: "/components/ThumbnailList",
    imageURL: "/ThumbnailList.avif",
    sections: ["Images & Icons"],
    additionalMatches: ["Gallery", "Image", "Photo"],
  },
  {
    title: "Tiles",
    to: "/components/Tiles",
    imageURL: "/Tiles.avif",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "Toast",
    to: "/components/Toast",
    imageURL: "/Toast.avif",
    sections: ["Status & Feedback"],
    additionalMatches: ["Alert", "Notification", "Flash", "Snackbar", "Message"],
  },
  {
    title: "Tooltip",
    to: "/components/Tooltip",
    imageURL: "/Tooltip.avif",
    sections: ["Overlays"],
    additionalMatches: ["Popup", "Hover", "Popover", "Info"],
  },
  {
    title: "Typography",
    to: "/components/Typography",
    imageURL: "/Typography.avif",
    sections: ["Text & Typography"],
  },
];

export const componentSections = [
  "Actions",
  "Forms & Inputs",
  "Images & Icons",
  "Layouts & Structure",
  "Lists & Tables",
  "Navigation",
  "Overlays",
  "Private",
  "Selections",
  "Status & Feedback",
  "Text & Typography",
  "Deprecated",
  "Primitives",
  "Themes",
  "Utilities",
] as const;

export const contentList: readonly ContentListItem[] = [
  {
    title: "Formatting",
    to: "/content/formatting",
    imageURL: "/Formatting.avif",
  },
  {
    title: "Product vocabulary",
    to: "/content/product-vocabulary",
    imageURL: "/Product Vocabulary.avif",
    additionalMatches: ["Words"],
  },
  {
    title: "Voice and tone",
    to: "/content/voice-and-tone",
    imageURL: "/Voice & Tone.avif",
  },
];

export const designList: readonly ContentListItem[] = [
  {
    title: "Animation",
    to: "/design/animation",
    imageURL: "/Animation.avif",
    additionalMatches: ["Motion"],
  },
  {
    title: "Borders",
    to: "/design/borders",
    imageURL: "/Borders.avif",
    additionalMatches: ["Dividers"],
  },
  {
    title: "Breakpoints",
    to: "/design/breakpoints",
    imageURL: "/Breakpoints.avif",
    additionalMatches: ["Responsive"],
  },
  {
    title: "Colors",
    to: "/design/colors",
    imageURL: "/Colors.avif",
    additionalMatches: ["Palette", "Colours"],
  },
  {
    title: "Elevations",
    to: "/design/elevations",
    imageURL: "/Elevations.avif",
    additionalMatches: ["Shadows"],
  },
  {
    title: "Opacity",
    to: "/design/opacity",
    imageURL: "/Opacity.avif",
  },
  {
    title: "Radii",
    to: "/design/radii",
    imageURL: "/Radii.avif",
    additionalMatches: ["Roundness", "Corners", "Radius"],
  },
  {
    title: "Spacing",
    to: "/design/spacing",
    imageURL: "/Spacing.avif",
    additionalMatches: ["Margin", "Padding"],
  },
  {
    title: "Typography",
    to: "/design/typography",
    imageURL: "/Typography.avif",
  },
];

export const hooksList: readonly ContentListItem[] = [
  {
    title: "useBool",
    to: "/hooks/useBool",
    sections: ["React Utilities"],
  },
  {
    title: "useBreakpoints",
    to: "/hooks/useBreakpoints",
    sections: ["Window & Layout"],
  },
  {
    title: "useCallbackRef",
    to: "/hooks/useCallbackRef",
    sections: ["React Utilities"],
  },
  {
    title: "useCollectionQuery",
    to: "/hooks/useCollectionQuery",
    sections: ["React Utilities"],
  },
  {
    title: "useDebounce",
    to: "/hooks/useDebounce",
    sections: ["React Utilities"],
  },
  {
    title: "useFocusTrap",
    to: "/hooks/useFocusTrap",
    sections: ["Accessibility"],
  },
  {
    title: "useInView",
    to: "/hooks/useInView",
    sections: ["Window & Layout"],
  },
  {
    title: "useIsMounted",
    to: "/hooks/useIsMounted",
    sections: ["React Utilities"],
  },
  {
    title: "useLiveAnnounce",
    to: "/hooks/useLiveAnnounce",
    sections: ["Accessibility"],
  },
  {
    title: "useOnKeyDown",
    to: "/hooks/useOnKeyDown",
    sections: ["Accessibility"],
  },
  {
    title: "useOnMount",
    to: "/hooks/useOnMount",
    sections: ["React Utilities"],
  },
  {
    title: "useRefocusOnActivator",
    to: "/hooks/useRefocusOnActivator",
    sections: ["Window & Layout"],
  },
  {
    title: "useResizeObserver",
    to: "/hooks/useResizeObserver",
    sections: ["Window & Layout"],
  },
  {
    title: "useStepper",
    to: "/hooks/useStepper",
    sections: ["React Utilities"],
  },
  {
    title: "useWindowDimensions",
    to: "/hooks/useWindowDimensions",
    sections: ["Window & Layout"],
  },
];

export const guidesList: readonly ContentListItem[] = [
  {
    title: "Welcome guide",
    to: "/guides/welcome-guide",
    sections: ["Getting started"],
  },
  {
    title: "Atlantis overview",
    to: "/guides/atlantis-overview",
    sections: ["Getting started"],
    imageURL: "/Overview.avif",
  },
  {
    title: "Contributing to Atlantis",
    to: "/guides/contributing",
    sections: ["Contributing"],
  },
  {
    title: "Repository contributing",
    to: "/guides/repository-contributing",
    sections: ["Contributing"],
  },
  {
    title: "Atlantis charter",
    to: "/guides/charter",
    sections: ["Contributing"],
  },
  {
    title: "Create a React component",
    to: "/guides/create-a-react-component",
    sections: ["Building"],
  },
  {
    title: "Customizing components",
    to: "/guides/customizing-components",
    additionalMatches: ["Custom", "Composability"],
    sections: ["Building"],
  },
  {
    title: "Writing documentation",
    to: "/guides/documentation-styleguide",
    sections: ["Contributing"],
  },
  {
    title: "Adding an icon",
    to: "/guides/adding-an-icon",
    sections: ["Contributing"],
  },
  {
    title: "Figma 101",
    to: "/guides/figma-101",
    sections: ["Getting started"],
    imageURL: "/Figma.avif",
  },
  {
    title: "Frontend styleguide",
    to: "/guides/frontend-styleguide",
    sections: ["Building"],
  },
  {
    title: "Getting started with React",
    to: "/guides/getting-started-with-react",
    sections: ["Getting started"],
    imageURL: "/React.avif",
  },
  {
    title: "Pull request title generator",
    to: "/guides/pull-request-title-generator",
    sections: ["Contributing"],
  },
  {
    title: "Page layouts",
    to: "/guides/page-layouts",
    sections: ["Building"],
  },
  {
    title: "Scaffolding",
    to: "/guides/scaffolding",
    sections: ["Building"],
  },
  {
    title: "Component support levels",
    to: "/guides/component-support-levels",
    sections: ["Building"],
    additionalMatches: ["Supported", "Beta", "Legacy", "Deprecated"],
  },
  {
    title: "Local linking",
    to: "/guides/local-linking",
    sections: ["Building"],
    additionalMatches: ["npm link", "symlink", "watch", "dev:link"],
  },
  {
    title: "Using Tailwind CSS",
    to: "/guides/using-tailwind",
    sections: ["Building"],
    additionalMatches: ["Tailwind", "tailwindcss", "atlantisPlugin", "tokens"],
  },
];

export const packagesList: readonly ContentListItem[] = [
  {
    title: "Components",
    to: "/packages/components",
  },
  {
    title: "Design",
    to: "/packages/design",
  },
  {
    title: "Eslint Config",
    to: "/packages/eslint-config",
  },
  {
    title: "Hooks",
    to: "/packages/hooks",
  },
  {
    title: "Stylelint Config",
    to: "/packages/stylelint-config",
  },
];

export const patternsList: readonly ContentListItem[] = [
  {
    title: "Interaction",
    to: "/patterns/interaction",
    imageURL: "/Interaction.avif",
  },
  {
    title: "Empty states",
    to: "/patterns/empty-states",
    imageURL: "/EmptyStates.avif",
  },
  {
    title: "Errors",
    to: "/patterns/errors",
    imageURL: "/Errors.avif",
  },
  {
    title: "Disabled states",
    to: "/patterns/disabled-states",
    imageURL: "/DisabledStates.avif",
  },
  {
    title: "Settings",
    to: "/patterns/settings",
    imageURL: "/Settings.avif",
  },
];

export const changelogList: readonly ContentListItem[] = [
  {
    title: "Upcoming Breaking Changes",
    to: "/changelog/breaking-changes",
    additionalMatches: ["Changelog", "Log", "Breaking", "Changes"],
  },
];
